name: Sync Trophy Stats
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour. Use '*/10 * * * *' for every 10 mins.
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab.

permissions:
  contents: write # Required for the bot to commit changes to your repo.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch StreamElements Data
        run: |
          # Fetch spturkey data using curl and parse with jq
          # Replace with your actual Account ID
          curl -s "https://api.streamelements.com/static/v2/channels/683d5f784b7b70b6bf43aacb/counters/spturkey" -o turkey_raw.json
          TURKEY_VAL=$(jq -r '.value' turkey_raw.json)

          # Update the 'current' field for 'spturkey' in trophies.json
          # This assumes your JSON structure: { "id": "spturkey", "current": 0, ... }
          jq --arg val "$TURKEY_VAL" '(.[] | select(.id == "spturkey") | .current) = ($val | tonumber)' trophies.json > trophies_updated.json && mv trophies_updated.json trophies.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add trophies.json
          # Only commit if there are changes to avoid workflow errors
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated trophy sync: $(date)" && git push)
